### ISSUE TITLE
ci.centos.org: missing retry to fetch node from Duffy

### ISSUE THREAD

**Issue by domcleal** [sclorg/sclo-ci-tests#13]
The jobs fail quickly and without much information when there aren't any Duffy nodes available on ci.centos.org.

<pre>
11:43:04 + cico node get -f value --arch x86_64 --release 6 --count 1 --api-key redacted
11:43:04 Starting new HTTP connection (1): admin.ci.centos.org
11:43:05 Resetting dropped connection: admin.ci.centos.org
11:43:05 'NoneType' object has no attribute '__getitem__'
11:43:05 + tail -n 1 cico.out
11:43:05 + cut -d ' ' -f 7
11:43:05 + tail -n 1 cico.out
11:43:05 + cut -d ' ' -f 2
11:43:05 [SCLo-sclo-vagrant1-sclo-C6-x86_64] $ /bin/sh -xe /tmp/hudson5276185328943795982.sh
11:43:05 ++ head -n 1 host
11:43:05 + h=
11:43:05 + cat
11:43:05 [SCLo-sclo-vagrant1-sclo-C6-x86_64] $ /bin/sh -xe /tmp/hudson5810737520869088600.sh
11:43:05 + scp -F ssh_config -rp tests/ host:tests/
11:43:05 ssh: Could not resolve hostname .ci.centos.org: Name or service not known
</pre>

The NoneType error is from cicoclient (https://github.com/dmsimard/python-cicoclient/issues/5), but it should be wrapped with a retry loop or better, have some retry functionality in cicoclient.

**Comment by hhorak** [comment]
The retry functionality is not in place, closing this.
