### ISSUE TITLE
devtoolset-6 6.1 candidate fails postgresql build due to hard-coded gcc 6.2 check

### ISSUE THREAD

**Issue by TBBle** [sclorg/sclo-ci-tests#22]
Looking at https://ci.centos.org/view/SCLo-pkgs-cbs/job/SCLo-pkg-devtoolset-6-rh-C7-candidate-x86_64/, it's been failing since build 42, when it started trying to build with devtoolset-6 6.1, including gcc 6.3.

The [postgresql build script](https://github.com/sclorg/sclo-ci-tests/blob/master/collections/devtoolset-6-rh/compile-postgresql/run.sh) has a hard-coded test for gcc 6.2.

The fix for last time was 30ba89c0fe9cfa10320ffd950699d50a8cadd421 which just changed the hardcoded version from 5.2|5.3 to 6.2.

The simplest fix would be to check for 6.2|6.3. I feel like a check for gcc 6.* would be better, since that's the [naming basis](https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/6/html/User_Guide/sect-Red_Hat_Developer_Toolset-About.html) of devtoolset-6.

**Comment by hhorak** [comment]
Thx, fixed by #23.
